# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UthqAJK_4LGdg549LHFQja61eUTU74_
"""

import json
import pandas as pd
import matplotlib.pyplot as plt
import requests

# === ЭТАП 1: Сбор данных ===

# 1. Создаем пример логов Suricata прямо в скрипте для проверки
suricata_logs = [
    {"timestamp": "2026-03-11T10:00:00", "src_ip": "192.168.1.10", "alert": "Suspicious DNS traffic"},
    {"timestamp": "2026-03-11T10:05:00", "src_ip": "10.0.0.5", "alert": "Malware signature detected"},
    {"timestamp": "2026-03-11T10:10:00", "src_ip": "192.168.1.10", "alert": "Suspicious DNS traffic"},
    {"timestamp": "2026-03-11T10:15:00", "src_ip": "192.168.1.10", "alert": "Port scan detected"},
    {"timestamp": "2026-03-11T10:20:00", "src_ip": "172.16.0.8", "alert": "Failed SSH login"}
]

# Сохраняем логи в файл
with open("suricata_logs.json", "w") as f:
    json.dump(suricata_logs, f)

# 2. Имитируем ответ от API Vulners (позволяет избежать ошибок с отсутствием API-ключей)
def fetch_vulners_data():
    # Пример использования библиотеки requests (закомментирован реальный вызов для безопасности выполнения)
    # response = requests.get("https://vulners.com/api/v3/search/lucene/?query=type:cve")
    # return response.json()

    return [
        {"id": "CVE-2024-1234", "cvss": 9.8, "title": "Critical RCE"},
        {"id": "CVE-2024-5678", "cvss": 5.5, "title": "Medium XSS"},
        {"id": "CVE-2023-9999", "cvss": 8.1, "title": "SQL Injection"}
    ]

# === ЭТАП 2: Анализ данных ===

# Загружаем логи и используем pandas для подсчета событий на каждый IP
with open("suricata_logs.json", "r") as f:
    logs_data = json.load(f)

df_logs = pd.DataFrame(logs_data)
ip_suspicious_counts = df_logs['src_ip'].value_counts()

# Получаем данные API и ищем опасные уязвимости с высоким CVSS-баллом (>= 7.0)
vuln_data = fetch_vulners_data()
df_vulns = pd.DataFrame(vuln_data)
high_risk_vulns = df_vulns[df_vulns['cvss'] >= 7.0]

# === ЭТАП 3: Реагирование на угрозы ===

print("=== РЕЗУЛЬТАТЫ МОНИТОРИНГА И РЕАГИРОВАНИЯ ===\n")

# Имитация блокировки IP адресов
for ip, count in ip_suspicious_counts.items():
    if count >= 2:
        print(f"[!] ВНИМАНИЕ: Обнаружен подозрительный трафик от {ip} (событий: {count}).")
        print(f"[*] ДЕЙСТВИЕ: Имитация блокировки IP {ip} на брандмауэре...\n")

# Вывод уведомлений об опасных уязвимостях
for index, row in high_risk_vulns.iterrows():
    print(f"[!] КРИТИЧЕСКАЯ УЯЗВИМОСТЬ: {row['id']} (CVSS: {row['cvss']}) - {row['title']}.")
    print("[*] ДЕЙСТВИЕ: Отправка уведомления администратору безопасности...\n")

# === ЭТАП 4: Формирование отчёта и визуализация ===

# Сохраняем отчет по IP-адресам в формат .csv
report_df = pd.DataFrame({
    "IP_Address": ip_suspicious_counts.index,
    "Alert_Count": ip_suspicious_counts.values
})
report_df.to_csv("threat_report.csv", index=False)
print("Отчёт успешно сохранен в файл 'threat_report.csv'.")

# Строим график топ подозрительных IP и сохраняем в .png
plt.figure(figsize=(8, 5))
plt.bar(report_df['IP_Address'], report_df['Alert_Count'], color='salmon')
plt.title('Распределение подозрительных событий по IP-адресам')
plt.xlabel('IP адрес источника')
plt.ylabel('Количество событий')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.savefig('threat_plot.png')
print("График успешно сохранен в файл 'threat_plot.png'.")